#!/bin/bash

if [ -z "$1" ]; then
    echo "Please provide a match"
    exit 1
fi

if [ ! -f "matches/$1.json" ]; then
    echo "Match $1 not found"
    exit 1
fi

cp "matches/$1.json" match.json
echo "Beginning match $1"
npm start
